services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn library.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: library.settings
      - key: DATABASE_URL
        fromDatabase:
          name: my-django-db
          property: connectionString
    preDeployCommand: |
      python manage.py migrate

databases:
  - name: my-django-db
    databaseName: mydb
    user: myuser
