# Generated by Django 5.2.1 on 2025-07-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'ordering': ['author_name']},
        ),
        migrations.AlterModelTable(
            name='authors',
            table='authors',
        ),
    ]
