# Generated by Django 5.2.1 on 2025-07-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='availability',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20),
        ),
    ]
